valory-xyz/trader-quickstart

trades.py
Update trades.py script:
- Addressed limitation of 1000 entries per query.
- Addressed invalid markets.
- Added dust check.
=> Update trades.py script

run_service.sh
=> Fix Python version check

run_service.sh
Update trader 0.6.2
Fixes redeeming functionality.
=> Update trader 0.6.2

run_service.sh
=> Bump to 0.6.5

run_service.sh, scripts/fix_interrupted_service_update.sh, stop_service.sh
Hotfix: interrupted service update
=> Fix interrupted service update

run_service.sh
Ensure script is robust against several on-chain registry failures
=> Ensure script is robust against on-chain registry failures

run_service.sh
This PR replaces `sed` with `awk` for better compatibilty with macOS.
=> fix: `add_volume_to_service` on macos

rank_traders.py, trades.py
=> Create ranking script

run_service.sh
Use a hackathon participant's strategy, which seems to be more profitable.
=> Update the trader's strategy

run_service.sh
=> Disable on-chain update

run_service.sh, scripts/fix_interrupted_service_update.sh
This PR adds support for using `trader@v0.7.0`.
=> chore: update run_service.sh to use `trader@v0.7.0`

run_service.sh
This PR makes the default response for hash change on non-staking path.
=> fix: hash change

run_service.sh
Improve staking UX: ask for OLAS once.
=> Improve staking UX: ask for OLAS once

run_service.sh, scripts/staking.py, scripts/utils.py
Fix unstaking issue
Addresses issue #94
=> Fix unstaking issues

run_service.sh, scripts/is_keys_json_password_valid.py
Adds a password verification step.
Note: This is to be merged on feat/security_script branch
=> Password verification

run_service.sh, scripts/staking.py
Improve staking UX
Addresses: #111 #116
=> Improve staking UX

run_service.sh, scripts/mech_events.py, scripts/staking.py
=> Review messages

trades.py
=> Fixes on trades.py

run_service.sh
This PR bumps to `trader@v0.10.0`.
=> Release `v0.10.0`

run_service.sh
=> Release v0.10.1

run_service.sh
This PR bumps to `trader@v0.10.3`.
=> chore: bump to `trader@v0.10.3`

run_service.sh
This PR bumps to `trader@v0.11.0`.
=> chore: update to `trader@v0.11.0`

run_service.sh
This PR releases `trader-quickstart@v0.11.0`.
=> Release `v0.11.0`

run_service.sh
=> Remove unused vars

run_service.sh
This PR bumps the quickstart to `trader@v0.11.3`.
=> chore: update to `trader@v0.11.3`

run_service.sh
This PR releases `trader-quickstart@v0.11.2`.
=> Release v0.11.2

README.md, run_service.sh, scripts/staking.py, terminate_on_chain_service.sh, trades.py
Terminate on-chain service suport
Addresses #174
=> Support to terminate on-chain service

run_service.sh
Remove trader repo if current downloaded version does not match.
Addresses https://github.com/valory-xyz/trader-quickstart/issues/145
=> Remove trader repo if version does not match

trades.py
Add guard clauses in trades.py
Addresses https://github.com/valory-xyz/trader-quickstart/issues/172
=> Add guard clauses in trades.py

trades.py
Fix an issue in trades script that made rank traders script crash.
=> Fix rank traders

run_service.sh
=> Fix staking checks

report.py
Fix report.py for Alpine staking program
=> Fix report.py for Alpine staking program

README.md, report.py
=> Release v0.12.0 (update)

scripts/staking.py
=> Fix staking check

README.md
=> Minor fix on README

terminate_on_chain_service.sh
=> Fix termination script

run_service.sh
=> Fix flaky staking issue

run_service.sh
=> Bump trader

run_service.sh
Increase sleep duration to avoid RPC out-of-sync issues
=> Increase sleep duration

run_service.sh
=> Fix sleep time

run_service.sh
Add explicit waits for RPC states. This ensures to wait (until a timeout) after an on-chain write operation, so that the RPC reports the expected value. By default, a timeout of 5 minutes is added. The timeout is not blocking, that is, the script will continue notifying the timeout, but if the state is incompatible, the script will fail as usual. 
Addresses #226
=> Add explicit waits for RPC states

run_service.sh
This PR updates the nevermined mech address to use the mech that offers dynamic pricing.
=> feat: use dynamic pricing mech

run_service.sh
Fix collection of incorrect hash to determine if the service needs to be re-minted
=> Fix incorrect hash

run_service.sh
=> Release v0.12.7.post1

run_service.sh
Using the default threshold now, which is set to 10 cents.
=> Bump the trader and remove the bet threshold's override

run_service.sh
https://github.com/valory-xyz/trader-quickstart/pull/244#discussion_r1511295358
=> Explicitly set the bet threshold

run_service.sh, scripts/mech_events.py, trades.py
=> Release v0.12.9

scripts/staking.py
Try re-stake service after eviction
Same changes as PR #252, but based on develop.
Previous behaviour:
If the service is evicted, the script will unstake it and run it unstaked. It will be staked once the script is re-run again.
New behaviour:
If the service is evicted, the script will unstake it and try to re-stake it immediately.
=> Try re-stake service after eviction

run_service.sh
=> Update Trader version

run_service.sh, scripts/staking.py
=> Release v0.13.1

run_service.sh
=> Update trader to v0.14.0

run_service.sh
Temporary fix mech_chain_id until the issue is solved at skill level.
=> Temporary fix mech_chain_id

run_service.sh
Change irrelevant tools following >= 74% accuracy on https://huggingface.co/spaces/valory/olas-prediction-leaderboard
Added irrelevant tools:
{'prediction-request-rag-claude', 'prediction-request-reasoning-claude', 'prediction-request-rag', 'claude-prediction-online', 'prediction-url-cot-claude', 'prediction-online-sme'}
Removed irrelevant tools:
{'prediction-offline-sme', 'prediction-online'}
=> Change irrelevant tools

run_service.sh
Reverts ca674f250d93a75b4f357ee03d3e67f84cf8cb13.
=> Decrease the minimum bet amount

run_service.sh
=> Add graph urls

run_service.sh
Changes the version set in #292.
=> Bump trader to `v0.16.0`

README.md, run_service.sh
=> Allow empty Subgraph API key

run_service.sh, scripts/staking.py, scripts/utils.py
=> Fix staking data type

rank_traders.py, trades.py
=> Fix script subgraph endpoints

run_service.sh
More info in paramiko/paramiko#2419.
=> Pin `cryptography` to avoid warnings from `paramiko`

report.py
Fix report.py to work with new staking contracts.
WARNING: It will not work for old (deprecated) staking contracts.
=> Fix report.py

run_service.sh
Fix issue with Safe for interrupted service updates on the on-chain flow.
=> Fix onchain flow

run_service.sh
https://github.com/valory-xyz/trader-quickstart/pull/375#discussion_r1819335464
=> Release non-multi-bet version

scripts/choose_staking.py
Enabling latest staking programmes Quickstart Beta - Expert 6 and Quickstart Beta - Expert 7
=> added new staking programmes 6 and 7

run_service.sh
Avoid using sed to support mac, and instead use a raw algorithm
closes #385
=> Fix: Avoid using sed to support mac

reset_staking.sh, run_service.sh, stop_service.sh, terminate_on_chain_service.sh
on some systems with codepages differs from utf-8 there are some problems with aea/autonomy based python code
=> force utf-8 with python

run_service.sh
Hotfix: fix sed command on main (causes issues on Mac)
=> Hotfix: fix sed command on main

README.md, report.py
Update the containers' names to reflect the changes in the latest `open-autonomy` framework version.
=> Fix hardcoded names of the docker containers

analyse_logs.py
Script iterates through all build directories to find logs
=> fix: check k8s and docker filepaths for logs

run_service.sh
=> chore: bump trader version
