- README.md
- trades.py
Added check for redeemed markets in `trades.py` script.
It should display information in this format:
```
------
Trades
------
Market:   https://aiomen.eth.limo/#/0xf29a2ce76935ba79caafd80bf48a56f32d679328
Question: Will the temperature in rome surpass 46 degrees celsius on 9 August 2023? [test question]
Bought:   0.1000 DAI for 0.2340 DAI 'yes' tokens
Fee:      0.0030 DAI
Earnings: 0.2340 DAI
Redeemed: True
Market:   https://aiomen.eth.limo/#/0xee4f1a5c61a6fbac9d11e237701606ee5ff78603
Question: Will the popularity of cold soups increase in New York City during the summer of 2023?
Bought:   0.0600 DAI for 0.0594 DAI 'Yes' tokens
Fee:      0.0006 DAI
Market not yet finalized.
-------
Summary
-------
Num. trades: 1 (0 pending finalization)
Invested:    0.1600 DAI
Fees:        0.0036 DAI …
```
> Added check for redeemed markets

- run_service.sh
Updated a clearer message when funds are required in a certain address. Example:
```
Your agent instance's address: 0x00000000000000000000000000000000000000001
Your service's Safe address: 0x00000000000000000000000000000000000000002
Checking balance of agent instance's address (minimum required 0.0500 DAI):
- Address: 0x00000000000000000000000000000000000000001
- Balance: 0.0509 DAI
OK.
Checking balance of service Safe's address (minimum required 0.5000 DAI):
- Address: 0x00000000000000000000000000000000000000002
- Balance: 0.4900 DAI
Please, fund address 0x00000000000000000000000000000000000000002 with at least 0.5000 DAI.
Waiting...   
- Updated balance: 0.5000 DAI
OK.
Detected an existing build. Using this one...
rm: cannot remove 'abci_build/nodes/node0/config/addrbook.json': …
```
> Update run_service.sh - improved message for required funds

- trades.py
> Improve statistics

- trades.py
Added number of winner trades per market state on trades.py summary script.
Added ROI to markets finalizing. Example:
```
--------------------------
Summary (per market state)
--------------------------
Open       Pending    Finalizing   Arbitrating        Closed         TOTAL
--------------------------------------------------------------------------------------------------
Num. trades                7            15            16             0           104           142
Winner trades              0             0             8             0            55            63
Invested            0.42 DAI      0.92 DAI      0.98 DAI      0.00 DAI      6.34 DAI      8.66 DAI
Fees                0.01 DAI      0.02 DAI      0.02 DAI      0.00 DAI      0.13 DAI      0.17 DAI
Earnings            0.00 …
```
> Added number of winner trades

- run_service.sh
This PR adds support for adding an extra volume to docker-compose file s.t. it can allow for persisting data across restarts.
> feat: add data volume to docker-compose

- run_service.sh
* Bump to trader 0.6.3
* Changed redeemed days
* Commented failing line on Mac (will be addressed in next release)
> Bump to trader 0.6.3

- run_service.sh
This PR adds support for using `trader@v0.6.6`.
> chore: update `run_service.sh` script to use `v0.6.6`

- README.md
- trades.py
Update trades summary script:
* Groups trades per market.
* Adds CLI flags `--from-date` and `--to-date` to filter trades by trade creation date.
* Refines the logic to determine if a trade has been redeemed.
> Update trades summary script

- run_service.sh
Refactor: use awk instead of grep -P
> Refactor: use awk instead of grep -P

- trades.py
> Fixes trades.py

- README.md
- scripts/change_keys_json_password.py
> Change password feature

- run_service.sh
This PR adds wxdai and xdai balances using python to avoid integer overflows.
> fix: add balances with python to avoid overflow

- run_service.sh
Adds a warm start to the policy to help convergence and improve tool selection. The data were obtained after many days of running the service.
> Add a warm start to the policy

- README.md
- run_service.sh
- scripts/fix_interrupted_service_update.sh
Adds missing details from #64 and #65.
> Add missing details

- run_service.sh
- scripts/update_service.py
This PR adds support for updating the on-chain service with the erc20 token.
> fix: update on-chain service with erc20 token

- run_service.sh
This PR adds a check for multisig address.
> feat: check for multisig address

- run_service.sh
With Getblock it is possible to run out of requests. This is not handled by the script yet and it gives this error:
Traceback (most recent call last):
File "<string>", line 1, in <module>
TypeError: string indices must be integers, not 'str'
This error is difficult to understand.
So I added a check for this edge case.
> Check RPC for available requests

- run_service.sh
Implements/fixes several RCP checks and displays an informative message rather than launching a Python exception.
* Checks for malformed RCP responses
* Checks for RCP out of calls
* Rearranges RCP check for eth_newFilter
Addresses issue #81
Merges user contribution #83
> Implements RPC checks

- README.md
- run_service.sh
Services without staking:
* Newly created services will use AGENT_ID=14
* Already created services will update AGENT_ID=12 -> AGENT_ID=14
Services with staking:
* Newly created services will use AGENT_ID=12
* Already created services will keep using AGENT_ID=12
Small improvements on README.md
> Fix on-chain agent IDs

- README.md
- rank_traders.py
- report.py
- scripts/mech_events.py
- trades.py
Implements a report script to have a quick healthcheck on service status and staking state.
To call the script, from the trader-quickstart main folder:
`cd trader; poetry run python ../report.py; cd ..`
A number of other scripts needed to be modified in order to accomodate the changes required by this script.
Also, the following improvement has been implemented in this PR: #127
> Report script

- run_service.sh
This PR bumps the trader to `v0.9.11`.
> chore: bump to `trader@v0.9.11`

- run_service.sh
This PR bumps the trader-quickstart to `trader@v0.9.13`.
> chore: bump to `trader@v0.9.13`

- run_service.sh
This PR bumps the quickstart to `trader@v0.10.0`.
> chore: bump to `trader@v0.10.0`

- run_service.sh
This PR bumps the trader-quickstart to v0.10.1.
> chore: bump to `trader@v0.10.1`

- run_service.sh
- terminate_on_chain_service.sh
Fix retries
- Increased retry timeout to 120 seconds
- Increased retries to 40 (ample margin, not reached usually)
- Fixed https://github.com/valory-xyz/trader-quickstart/issues/98. This fix was required to stop capturing output in useless variable, in order to allow seeing log messages comming from the framework.
- Updated trader version
NOTE: Needs a trader version which integrates these changes from Open Autonomy: https://github.com/valory-xyz/open-autonomy/pull/2140
> Fix retries (and update trader version)

- run_service.sh
- scripts/swap_safe_owner.py
> Fix typing list

- run_service.sh
- scripts/swap_safe_owner.py
> Release v0.12.5

- run_service.sh
- scripts/swap_safe_owner.py
> Release 0.12.4.post1

- run_service.sh
> Release v0.12.4.post2

- README.md
- report.py
- scripts/mech_events.py
- trades.py
Update mech_events to use subgraph
> Update mech_events to use subgraph

- run_service.sh
It was incorrect because:
1. It started the counts from 1.
2. Since the counts were non-zero, it should include all the relevant tools, because otherwise they would be initialized with `0`. For example, it did not include `claude-prediction-online`.
> Fix warm start

- trades.py
Fix duplicate mech calls
Addressess issue #232
> Fix duplicate mech calls

- run_service.sh
Fixes issue when creating a new service: the waiting function was used an unparsed string for `service_id` which was causing incorrect information being displayed on the console.
Addresses https://github.com/valory-xyz/trader-quickstart/issues/243.
> Collect correct service ID

- scripts/mech_events.py
- trades.py
Fix mech calls between dates
Addresses https://github.com/valory-xyz/trader-quickstart/issues/247
> Fix mech calls between dates

- scripts/staking.py
Unstake old contracts.
The script should unstake from old contracts specified in a dictionary. Note that ABIs might be slightly different on different staking programs.
> Unstake old contracts

- run_service.sh
- scripts/mech_events.py
Fix mech events script.
Fix variable initialization that caused wrong staking contract being called.
> Fix mech events script and variable initialization

- run_service.sh
The minimum bet threshold was accidentally increased in the previous release.
> Fix release `v0.14.5`

- trades.py
Fixes the analysis of the `trades.py` script.
Previously, the script was increasing the calculated redeemed earnings:
https://github.com/valory-xyz/trader-quickstart/blob/b1dc67542804d53bde9fdea9645c035324a9d071/trades.py#L737
only when the market was not invalid:
https://github.com/valory-xyz/trader-quickstart/blob/b1dc67542804d53bde9fdea9645c035324a9d071/trades.py#L723
However, the calculated earnings were increased in both cases:
https://github.com/valory-xyz/trader-quickstart/blob/b1dc67542804d53bde9fdea9645c035324a9d071/trades.py#L742
Therefore, this was a mistake in the calculation. The code now also accounts for the redeemed invalid markets.
:information_source: As an additional note, the script appears to be missing separate rows for the invalid markets, which would enhance …
> Also account for the redeemed invalid markets

- run_service.sh
Bumps the trader to `v0.17.0` and addresses the breaking changes.
Unfortunately getting lots of warnings after the update, due to https://github.com/paramiko/paramiko/issues/2419.
> Bump the trader to `v0.17.0`

- run_service.sh
This PR bumps the trader-quickstart to use `trader@v0.17.2`.
> bump: trader@v0.17.2

- run_service.sh
Fix export variables on MinGW. This PR changes the way variables are exported.
A specific check is used for Mac. Rest of the systems (Linux, WSL2, MinGW) use the default mechanism. Note that WSL2 reports the same `uname` as Ubuntu (`Linux`), therefore it was not causing an issue there.
> Fix export variables on MinGW

- README.md
- reset_staking.sh
- run_service.sh
- scripts/choose_staking.py
- scripts/get_agent_bond.py
- scripts/staking.py
- scripts/utils.py
> Update new staking contracts

- run_service.sh
- scripts/get_agent_bond.py
- scripts/staking.py
Read agent bond from registry when the service is not token secured
Addresses #346
> Read agent bond from registry when the service is not token secured

- scripts/staking.py
Revert condition for unstaking early introduced in PR #350
https://github.com/valory-xyz/trader-quickstart/pull/350/files#diff-ff2b1400d3292ccf632584d149b6808f071cf2d8dda5e0cad196034d88206634R73-R76
(Services cannot be unstaked early if evicted.)
> Fix check unstaking condition for evicted services

- README.md
- run_service.sh
> Generate k8s deployments

- README.md
- reset_staking.sh
- run_service.sh
- scripts/choose_staking.py
- scripts/staking.py
- terminate_on_chain_service.sh
Allow skipping user prompts in the QS
> Feat: `--attended=false` to skip user prompts

- README.md
- claim_olas.sh
- scripts/claim.py
> Claim script

- scripts/mech_events.py
> Use GQL for mech events

- scripts/choose_staking.py
- scripts/get_agent_bond.py
> Remove blockscout dependency

- README.md
- run_service.sh
Avoid unstaking happening automatically when the image hash changes (in unattended mode)
> Fix: Not unstake when `--attended=false`

- README.md
- claim_staking_rewards.sh
- scripts/claim_staking_rewards.py
Added support to claim OLAS staking rewards for password protected keys.
> Allow claiming olas staking rewards for password protected keys

- README.md
- claim_staking_rewards.sh
- scripts/claim_staking_rewards.py
Integrate walterriddler contribution: Allow claiming olas staking rewards for password protected keys
> Integrate walterriddler contribution: Allow claiming olas staking rewards for password protected keys

- run_service.sh
The previous command would fail with specific inputs, e.g., `5T_T`:
```
build_dir=abci_build_5T_T
echo ${build_dir##*_}
T
```
```
build_dir=abci_build_5T_T
echo ${build_dir#*build_}
5T_T
```
> Fix service id extraction

- README.md
~Please merge this PR only after merging https://github.com/valory-xyz/quickstart/pull/31 to `main`, because the link to the migration script is made available from `main`.~
The migration script update will be made later when it's ready, we can redirect the new users for now.
> chore: redirect to new quickstart

- terminate_on_chain_service.sh
This fixes a bug reported by a user. The terminate script was failing if the quickstart had a password.
> Fix: Terminate with password
